# --------------------------------------------------------------------------------------------------
# Copyright 2026-present The Mystic Framework Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# --------------------------------------------------------------------------------------------------
# File: MysticVersion.cmake
# Description: This function reads the version information setup by MysticProject and outputs
# generated_cmake_version.hpp file with the version information. It is then read by Version library
# to provide version information to the application.
# Author: thedevmystic (Surya) <thedevmystic@gmail.com>
# License: Apache License 2.0
# --------------------------------------------------------------------------------------------------
# Usage:
# # Include this module in your CMakeLists.txt file:
# include(MysticVersion)
# # Call the mystic_version function to generate the version header file:
# mystic_version()
# # ... After targets have been defined ...
# # Call the mystic_version_add_library function to add the generated version header to a target
# mystic_version_add_library(<TARGET_NAME>)
# --------------------------------------------------------------------------------------------------

include("${CMAKE_CURRENT_LIST_DIR}/MysticMessage.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/PrivateHelpers.cmake")

# --------------------------------------------------------------------------------------------------
# Function: mystic_version
# Description: This function reads the version information setup by MysticProject and outputs
# generated_cmake_version.hpp file with the version information. It is then read by Version library
# to provide version information to the application.
# Args:
#   None
# --------------------------------------------------------------------------------------------------
function(mystic_version)
  # Get project prefix
  get_property(PROJECT_PREFIX DIRECTORY PROPERTY _MYSTIC_PROJECT_PREFIX)

  if(NOT PROJECT_PREFIX)
    mystic_message(FATAL_ERROR "Project prefix not set. Ensure that 'mystic_project' is called before 'mystic_version'.")
  endif()

  # Get version information from the project
  # x.y.z -> x.y.z.0
  # x.y -> x.y.0
  # This ensures we have at least 3 components for the version.
  set(NORMALIZED_VERSION "${${PROJECT_PREFIX}_PROJECT_VERSION}.0")

  # Split the version into components
  string(REPLACE "." ";" VERSION_COMPONENTS "${NORMALIZED_VERSION}")

  # Extract major, minor, and patch versions
  list(GET VERSION_COMPONENTS 0 VERSION_MAJOR)
  list(GET VERSION_COMPONENTS 1 VERSION_MINOR)
  list(GET VERSION_COMPONENTS 2 VERSION_PATCH)

  # Generate the version header file
  _mystic_generate_random_string(8 RANDOM_STRING)
  set(VERSION_HEADER_PATH "${CMAKE_CURRENT_BINARY_DIR}/generated_cmake_version.hpp")
  file(WRITE "${VERSION_HEADER_PATH}" "// This file is auto-generated by CMake.\n// DO NOT EDIT MANUALLY.\n\n")
  file(APPEND "${VERSION_HEADER_PATH}" "#ifndef GENERATED_CMAKE_VERSION_HPP_${RANDOM_STRING}\n#define GENERATED_CMAKE_VERSION_HPP_${RANDOM_STRING}\n\n")
  file(APPEND "${VERSION_HEADER_PATH}" "#define MYSTIC_CMAKE_VERSION_MAJOR ${VERSION_MAJOR}\n")
  file(APPEND "${VERSION_HEADER_PATH}" "#define MYSTIC_CMAKE_VERSION_MINOR ${VERSION_MINOR}\n")
  file(APPEND "${VERSION_HEADER_PATH}" "#define MYSTIC_CMAKE_VERSION_PATCH ${VERSION_PATCH}\n\n")
  file(APPEND "${VERSION_HEADER_PATH}" "#endif  // GENERATED_CMAKE_VERSION_HPP_${RANDOM_STRING}\n")
endfunction()

# --------------------------------------------------------------------------------------------------
# Function: mystic_version_add_library
# Description: This is a helper function that adds generated_cmake_version.hpp to the specified
# target. It ensures that the version header is included in the target's include directories.
# Args:
#   TARGET: The name of the target to which the version header should be added.
# --------------------------------------------------------------------------------------------------
function(mystic_version_add_library TARGET)
  if(NOT TARGET)
    mystic_message(FATAL_ERROR "Target name not provided. Usage: mystic_version_add_library(<TARGET_NAME>)")
  endif()

  # Add the generated version header to the target's include directories
  target_include_directories(${TARGET} PRIVATE "${CMAKE_CURRENT_BINARY_DIR}")

  # Add generated_cmake_version.hpp to the target's sources to ensure it's compiled
  target_sources(${TARGET} PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/generated_cmake_version.hpp")
endfunction()
